# Generated by Django 6.0.3 on 2026-03-07 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_last_changed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
